services:
  mysql:
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: totallyunsafe
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "2000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: totallyunsafe
  apache:
    build: ./docker/apache
    container_name: apache
    depends_on:
      - mysql
    volumes:
      - ./source:/var/www/html/
    ports:
      - "8080:80"

  node:
    image: node:18
    container_name: node
    volumes:
      - ./:/cwd
    working_dir: /cwd/ts
    command: npm run watch
    environment:
      - npm_config_cache=/home/node

  composer:
    image: composer:2
    container_name: composer
    volumes:
      - ./:/cwd
    working_dir: /cwd
    command: composer install && composer dump-autoload
