on: 
  push:
    branches:
      - main
name: Deploy
jobs:
  buildAnddeploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📦 Bundle client side scripts
      run: docker run -v ${{ github.workspace }}:/app node:18 sh -c "cd /app/ts && npm ci && npm run build"       
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./source/
        exclude: |
          **/env.php
          **/tests/*Test.php